### 1.Model
model:
  name: "icnet"
  backbone: "resnet50"

### 2.Optimizer
optimizer:
  init_lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005

### 3.Trainning 
train:
  specific_gpu_num: "1"     # for example: "0", "1" or "0, 1"
  train_batch_size: 16      # adjust according to gpu resources
  valid_batch_size: 16
  data_path: "../data/sunrgbd/"
  epochs: 100
  log_iter: 10        # print log every log-iter 
  val_epoch: 1        # run validation every val-epoch
  ckpt_dir: "./ckpt/" # ckpt and trainning log will be saved here

### 4.Test
test:
  # ckpt_path: "./ckpt/icnet_resnet50_197_0.710_best_model.pth" # set the pretrained model path correctly